### ISSUE TITLE
Question: send-cli as library

### ISSUE THREAD

**Issue by dsnezhkov** [ehuggett/send-cli#11]
Hello,

Thank you for this project. I had a need to use this functionality as a library a few months back. I have modified the client manually to accomplish this (e.g. changed the imports, etc. ) However, I wanted to ask if there are plans to support this as a library longer term? Or perhaps, there is some guidance on how to properly do this going forward?

This is was my use case:
```
import send_cli.common
import send_cli.download
import send_cli.upload

data, key, iv = send_cli.upload.encrypt(fh)
link = send_cli.upload.put(service,data,filename,iv)

data, filename, key, iv, tag = send_cli.download.get(link)
tmpfile = send_cli.download.decrypt(data, key, iv, tag)
```
Thank you.

**Comment by dsnezhkov** [comment]
I found some guidance in the test suite. Thanks

**Comment by ehuggett** [comment]
I would be very interested in any feedback you have about how your use case could be better accommodated. It looks like your testing that a file uploaded to send can be retrieved?

I would like to turn this project into a 'good' library. I've been very hesitant to start reorganising/rewriting everything under `sendclient/` as I'm not at all confident I know how best to achieve this (I was looking into it but I haven't done anything recently).

**Comment by dsnezhkov** [comment]
Yes. Actually, the current `sendclient` is convenient and provides enough abstraction for me at the moment. I think I can just as easily use `upload.send_file` call rather than dropping down to the implementation routines that `sendclient` itself abstracts out (e.g. direct encrypt/decrypt ). 

What I would very much benefit from, since I am using `sendclient.*` calls is some level of message verbosity suppression. I  know download progress and statistics on file size transferred are very valuable in case of an end client. However, using `sendclient` as a library, it would be ideal if I can just inspect the returns from 

`ffsend_link, fileId, delete_token = sendclient.upload.send_file(
                            service, sfile, ignoreVersion=False, fileName=None)` itself which looks like it is already possible. 

Perhaps, verbosity level could be adjusted with something like a `logging` package, and/or a parameter to suppress printed feedback on request.   Thank you.

**Comment by ehuggett** [comment]
I've copied your suggestion into a new issue so it doesn't get lost. Thanks!
