### ISSUE TITLE
Make a package for pip

### ISSUE THREAD

**Issue by yvan-sraka** [ehuggett/send-cli#2]
Hello,

Looking for a command line tool to use Firefox Send, I found your work here https://github.com/mozilla/send/issues/403! I think it might be nice to make a package available on [PyPI](https://pypi.python.org/pypi) to allow users to install this tool more easily through `pip install send-cli`. What do you think?

**Comment by subu28** [comment]
I would like to try this out. I will send a PR within a week.

**Comment by ehuggett** [comment]
I've been hesitant to do this as I wasn't sure what I intended to do with this project long term, but I've been thinking about it and I suspect it won't take too much time/effort to keep it working with the latest version of Send so sure, why not, I'll publish it into the python package index 😄 

Thanks for taking an interest @subu28, do you have anything in progress? I'm going to come back to this after closing #1

**Comment by subu28** [comment]
Hey, I haven't started. Will not be able to start this weekend as well.

Regards
Subhash Sridharan

________________________________

**Comment by ehuggett** [comment]
Thanks for the quick response, I didn't want to duplicate any effort! I've made a new branch for this, https://github.com/ehuggett/send-cli/tree/package , so you will be able to see what I have done so far if you want to improve or add to it

- added requirements.txt, generated by running `pip freeze` after installing the required packages in a virtualenv.

todo
- `certifi==2017.7.27.1 chardet==3.0.4 idna==2.6` probably shouldn't be in requirements.txt, I suspect they are dependencies of one of the requirements?
- Check if I should relax the version requirements, ie use minimum versions

**Comment by ehuggett** [comment]
https://github.com/ehuggett/send-cli/tree/travis-pytest has a basic (incomplete?) setup.py

**Comment by ehuggett** [comment]
I uploaded a package to the Test PyPI Server, if anyone cares to try it

```bash
virtualenv tmp
source tmp/bin/activate
pip install --extra-index-url https://testpypi.python.org/pypi sendclient
send-cli -h

# and when your done (you can also delete the tmp directory, or keep it to use again)
deactivate
```

**Comment by ehuggett** [comment]
send v2 just appeared on production (with password support), I will hopefully publish the package early next week

**Comment by ehuggett** [comment]
Published as "sendclient" https://pypi.python.org/pypi/sendclient/

After installing the package with pip, you should find send-cli is in your $PATH

**Comment by HLFH** [comment]
@ehuggett You should precise it in the `README.md`, that we can do `pip install sendclient` to use `send-cli`.

**Comment by ehuggett** [comment]
@HLFH thanks for pointing that out, Its now in the readme ae93aad40dcf67a4122bba780c0fe8a55cefd209
