### ISSUE TITLE
Add option to delete a uploaded file

### ISSUE THREAD

**Issue by ehuggett** [ehuggett/send-cli#6]
thanks to @skorov for contributing the delete function in #5

the command line parameter(s) will need to accept the deleteToken and either the fileId or the download url.

note: In a future version of send, it would be nice if the authKey was used (and the delete Token removed) so that the download url can be used to delete a file (fileId and secretKey).

**Comment by skorov** [comment]
Happy to help. 😀

I think the purpose of the delete token is so that a receiver cannot delete the file. E.g. If Send was tuned to accept 3 downloads instead of one, you'd want all 3 people to download without the first person having the ability to delete.

On the topic of user input, might be easiest to retrieve the file ID from the user supplied download URL, since the file_id is never output to the user on its own.

**Comment by ehuggett** [comment]
True, but any one of the recipients could download the file 3 times 😄 

Getting the fileid from the download url would also fit nicely with a fallback for if the user has lost the deleteToken that i've been thinking about, simply downloading and discarding the file. How about
- `--delete` to accept the url, as part of the argparse `action` group (currently file/stdin/url)
- `--delete-token` to accept the required for now (but potentially optional in the future) token.

note: (separate point) i've been meaning to add `api_exists()` which could have been useful for a better error message when trying to delete an expired/non-existent file (possibly exposing it as `--exists <url>` in send-cli too).

> Happy to help. 😀

If that's an offer please feel free, Thank you!  Either way I'll make sure this is closed before the first version of the [package](https://github.com/ehuggett/send-cli/issues/2) is published so that it can make use of your existing contribution, but please don't feel obliged

I'll always try to assign the issue to myself before doing anything on my own, in this case it won't be until after I've taken the time to recheck what I need to do to publish on pypi.

**Comment by ehuggett** [comment]
77149acf7041883ccca21c3bcd8a644415435f36 send-cli can delete a file using the delete token!

argparse lent itself to the syntax `--delete url token` so I'm not using the separate`--delete-token` option as I previously suggested.

Thanks again @skorov
